### ISSUE TITLE
和风api更新了

### ISSUE THREAD

**Issue by Kutius** [Revincx/wechat-miniapp-weather#1]

**Comment by Revincx** [comment]
这个只是之前当作业写的，不打算维护
可以看一下这个修改后的：https://github.com/skyilz/wechat-miniapp-weather

**Comment by Kutius** [comment]
> 这个只是之前当作业写的，不打算维护
> 可以看一下这个修改后的：https://github.com/skyilz/wechat-miniapp-weather

感谢
